#!/bin/sh
#
# This installs Homebrew and some useful packages.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Install a few Homebrew packages
brew install git git-sh node postgresql rbenv ruby-build tree

# Install Slate window manager
cd /Applications && curl http://www.ninjamonkeysoftware.com/slate/versions/slate-latest.tar.gz | tar -xz

exit 0
